/*--测试代码
INSERT INTO Building_ResourceQuantity(BuildingType,ResourceType,Quantity)
SELECT 'BUILDING_PALACE','RESOURCE_ELECTRICITY',500 UNION ALL
SELECT 'BUILDING_PALACE','RESOURCE_CONSUMER',500 UNION ALL
SELECT 'BUILDING_PALACE','RESOURCE_MANPOWER',500 UNION ALL
SELECT 'BUILDING_PALACE','RESOURCE_TITANIUM',500 UNION ALL
SELECT 'BUILDING_PALACE','RESOURCE_IRON',500 UNION ALL
SELECT 'BUILDING_PALACE','RESOURCE_COAL',500 UNION ALL
SELECT 'BUILDING_PALACE','RESOURCE_ALUMINUM',500 UNION ALL
SELECT 'BUILDING_PALACE','RESOURCE_OIL',500 UNION ALL
SELECT 'BUILDING_PALACE','RESOURCE_LUMBER',500 UNION ALL
SELECT 'BUILDING_PALACE','RESOURCE_GUNPOWDER',500 UNION ALL
SELECT 'BUILDING_PALACE','RESOURCE_HORSE',500 UNION ALL
SELECT 'BUILDING_PALACE','RESOURCE_URANIUM',500;

INSERT INTO Unit_FreePromotions(UnitType, PromotionType)
SELECT 'UNIT_SPARTAN300' , 'PROMOTION_SPARTAN300_FIGHT_TO_THE_END' UNION ALL
SELECT 'UNIT_CITADEL_EARLY' , 'PROMOTION_FORT_DESTRUCTION_OF_WORKS' UNION ALL
SELECT 'UNIT_DREADNOUGHT' , 'PROMOTION_BATTLESHIP_SECONDARY_GUN' UNION ALL
SELECT 'UNIT_BATTLESHIP' , 'PROMOTION_BATTLESHIP_SECONDARY_GUN';*/

--增加一个UnitPromotions的列来让这些不可选晋升仍然显示在晋升树里面
ALTER TABLE UnitPromotions ADD COLUMN ShowInPT integer not null default 0;
UPDATE UnitPromotions SET ShowInPT = 1 WHERE 
--舰炮齐射
Type = 'PROMOTION_SHIPBORNE_GUN_SALVO' OR
--旗舰锁定
Type = 'PROMOTION_FLAGSHIP_LOCKING' OR
--心战强化
Type = 'PROMOTION_EXP_ADAPT_4' OR
--海空神剑
Type = 'PROMOTION_AIR_EXCALIBUR' OR
--向死而生
Type = 'PROMOTION_AIR_TO_DIE_AND_LIVE';

--开启单位升级事件、产生事件、溅射、穿透
UPDATE CustomModOptions SET Value = 1 WHERE Name = 'EVENTS_UNIT_UPGRADES';
UPDATE CustomModOptions SET Value = 1 WHERE Name = 'EVENTS_UNIT_CREATED';
UPDATE CustomModOptions SET Value = 1 WHERE Name = 'PROMOTION_SPLASH_DAMAGE';
UPDATE CustomModOptions SET Value = 1 WHERE Name = 'PROMOTION_COLLATERAL_DAMAGE';

--航母机位拓展晋升的前置科技和航母的前置科技相同
UPDATE UnitPromotions SET TechPrereq = (SELECT PrereqTech FROM Units WHERE Type = 'UNIT_CARRIER')  WHERE Type = 'PROMOTION_FLIGHT_DECK_EXPAND_1';
UPDATE UnitPromotions SET TechPrereq = (SELECT PrereqTech FROM Units WHERE Type = 'UNIT_NUCLEAR_CARRIER')  WHERE Type = 'PROMOTION_FLIGHT_DECK_EXPAND_2';
UPDATE UnitPromotions SET TechPrereq = (SELECT PrereqTech FROM Units WHERE Type = 'UNIT_SUPER_CARRIER')  WHERE Type = 'PROMOTION_FLIGHT_DECK_EXPAND_3';

--替换柏柏尔图标
UPDATE UnitPromotions SET IconAtlas = 'QY_EXPROMOTION_ATLAS', PortraitIndex = '32' WHERE Type ='PROMOTION_NUMIDIAN_MARCH';

--柏柏尔每消耗一点移动力+3%伤害
UPDATE UnitPromotions SET MoveUsedAttackMod = '3' WHERE Type = 'PROMOTION_NUMIDIAN_MARCH';
UPDATE Language_zh_CN 
SET Text = '每消耗一点[ICON_MOVES]移动力，攻击伤害+3%。[NEWLINE]能够切换为双倍[ICON_MOVES]移动模式，但本回合无法[COLOR_NEGATIVE_TEXT]攻击[ENDCOLOR]。'
WHERE Tag = 'TXT_KEY_PROMOTION_NUMIDIAN_MARCH_HELP';

--屏蔽俾斯麦和大黄蜂的标记晋升显示
UPDATE UnitPromotions SET ShowInUnitPanel = 0 WHERE Type = 'PROMOTION_UNIT_ELITE_BATTLECRUISER_MARK';
UPDATE UnitPromotions SET ShowInUnitPanel = 0 WHERE Type = 'PROMOTION_UNIT_HORNET_MARK';

--UI晋升图标显示前置
INSERT OR REPLACE INTO IconFontTextures(IconFontTexture,IconFontTextureFile)
SELECT 'ICON_FONT_TEXTURE_QY_EXPROMOTION','QYPromotionFontIcons';

/*INSERT OR REPLACE INTO IconFontMapping(IconName,IconFontTexture,IconMapping) 
SELECT 'ICON_PROMOTION_QY_EXPROMOTION_' || CAST(PortraitIndex+1 AS TEXT),'ICON_FONT_TEXTURE_QY_EXPROMOTION',PortraitIndex+1 
FROM UnitPromotions WHERE IconAtlas = 'QY_EXPROMOTION_ATLAS';

CREATE TRIGGER QY_EXPromotion_IconFontMapping
AFTER INSERT ON UnitPromotions
WHEN NEW.IconAtlas = 'QY_EXPROMOTION_ATLAS'
BEGIN
    INSERT OR REPLACE INTO IconFontMapping(IconName,IconFontTexture,IconMapping) 
    SELECT 'ICON_PROMOTION_QY_EXPROMOTION_' || CAST(NEW.PortraitIndex+1 AS TEXT),'ICON_FONT_TEXTURE_QY_EXPROMOTION',NEW.PortraitIndex+1;
END;*/