--BUG规避
--统一前置
UPDATE UnitPromotions SET PromotionPrereqOr1 = PromotionPrereq
WHERE PromotionPrereq IS NOT NULL AND PromotionPrereqOr1 IS NULL;
UPDATE UnitPromotions SET PromotionPrereq=NULL;
--删除重复列
DELETE FROM UnitPromotions_UnitCombats
WHERE rowid NOT IN (SELECT min(rowid) FROM UnitPromotions_UnitCombats GROUP BY PromotionType,UnitCombatType);

--有部分晋升，其前置晋升已经和前一个晋升不相似,需要额外处理,否则无法正确显示
--DROP TABLE SpecialRulePromotion;
CREATE TABLE IF NOT EXISTS SpecialRulePromotion(SpecialPromotion text PRIMARY KEY DEFAULT NULL);
INSERT INTO SpecialRulePromotion(SpecialPromotion)
--空中修理
SELECT 'PROMOTION_AIR_REPAIR' UNION ALL
--装甲一级
SELECT 'PROMOTION_ARMOR_7' UNION ALL
--舰炮齐射
SELECT 'PROMOTION_SHIPBORNE_GUN_SALVO' UNION ALL
--攻坚
SELECT 'PROMOTION_SIEGE6' UNION ALL
--贯穿火力-闪击战术
SELECT 'PROMOTION_PENETRATES' UNION ALL
--天空神剑
SELECT 'PROMOTION_AIR_EXCALIBUR';


CREATE TABLE IF NOT EXISTS UnitCombatInfosEx (
    CombatClass text DEFAULT NULL, 
    --Description text REFERENCES Language_zh_CN(Tag),
    --DefaultUnitType text REFERENCES Units(Type),
    Description text ,
    DefaultUnitType text ,
    IsDefault boolean DEFAULT false,
    --BasePromotion text DEFAULT NULL REFERENCES UnitPromotions(Type));
    BasePromotion text DEFAULT NULL );

INSERT INTO UnitCombatInfosEx(CombatClass,Description,DefaultUnitType,IsDefault,BasePromotion)
--民兵(包括绿水海军)
SELECT 'UNITCOMBAT_RECON','TXT_KEY_PROMOTION_MILITIA_COMBAT','UNIT_WARRIOR','true','PROMOTION_MILITIA_COMBAT' UNION ALL
--侦察单位(包括轻帆船)
SELECT 'UNITCOMBAT_RECON','TXT_KEY_PROMO_MOD_DESC_RECON','UNIT_SCOUT','false','PROMOTION_RECON_UNIT' UNION ALL

--重装步兵
SELECT 'UNITCOMBAT_MELEE','TXT_KEY_PROMOTION_INFANTRY_COMBAT','UNIT_SWORDSMAN','false','PROMOTION_INFANTRY_COMBAT' UNION ALL
--火药步兵
SELECT 'UNITCOMBAT_MELEE','TXT_KEY_PROMOTION_GUNPOWDER_INFANTRY_COMBAT','UNIT_MUSKETMAN','false','PROMOTION_GUNPOWDER_INFANTRY_COMBAT' UNION ALL
--方阵步兵
SELECT 'UNITCOMBAT_MELEE','TXT_KEY_PROMOTION_ANTI_MOUNTED','UNIT_SPEARMAN','false','PROMOTION_ANTI_MOUNTED' UNION ALL
--反装甲单位
SELECT 'UNITCOMBAT_MELEE','TXT_KEY_PROMOTION_ANTI_TANK','UNIT_ANTI_TANK_GUN','false','PROMOTION_ANTI_TANK' UNION ALL
--陆军远程
SELECT 'UNITCOMBAT_SIEGE','TXT_KEY_PROMOTION_ARCHERY_COMBAT','UNIT_ARCHER','false','PROMOTION_ARCHERY_COMBAT' UNION ALL
--防空单位
SELECT 'UNITCOMBAT_SIEGE','TXT_KEY_PROMOTION_ANTI_AIR','UNIT_ANTI_AIRCRAFT_GUN','false','PROMOTION_ANTI_AIR' UNION ALL
--攻城武器
SELECT 'UNITCOMBAT_SIEGE','TXT_KEY_PROMOTION_CITY_SIEGE','UNIT_CATAPULT','false','PROMOTION_CITY_SIEGE' UNION ALL
--重装骑兵
SELECT 'UNITCOMBAT_MOUNTED','TXT_KEY_PROMOTION_KNIGHT_COMBAT','UNIT_HORSEMAN','false','PROMOTION_KNIGHT_COMBAT' UNION ALL
--坦克
SELECT 'UNITCOMBAT_ARMOR','TXT_KEY_PROMOTION_TANK_COMBAT','UNIT_WWI_TANK','false','PROMOTION_TANK_COMBAT' UNION ALL
--陆军游猎
SELECT 'UNITCOMBAT_HELICOPTER','TXT_KEY_PROMOTION_HITANDRUN','UNIT_CHARIOT_ARCHER','false','PROMOTION_HITANDRUN' UNION ALL
--直升机
SELECT 'UNITCOMBAT_HELICOPTER','TXT_KEY_PROMOTION_HELI_ATTACK','UNIT_HELICOPTER_GUNSHIP','false','PROMOTION_HELI_ATTACK' UNION ALL
--陆军AOE
SELECT 'UNITCOMBAT_BOMBER','TXT_KEY_PROMOTION_SPLASH_DAMAGE','UNIT_KATYUSHA','false','PROMOTION_SPLASH_DAMAGE' UNION ALL
--陆军特战
SELECT 'UNITCOMBAT_GUN','TXT_KEY_PROMOTION_SPECIAL_FORCES_COMBAT','UNIT_NATIONAL_GUARD','false','PROMOTION_SPECIAL_FORCES_COMBAT' UNION ALL

--海军近战
SELECT 'UNITCOMBAT_NAVALMELEE','TXT_KEY_PROMOTION_NAVALMELEE_COMBAT','UNIT_GALLEASS','false','PROMOTION_NAVALMELEE_COMBAT' UNION ALL
--驱逐舰
SELECT 'UNITCOMBAT_NAVALMELEE','TXT_KEY_PROMOTION_DESTROYER_COMBAT','UNIT_DESTROYER','false','PROMOTION_DESTROYER_COMBAT' UNION ALL
--海军远程
SELECT 'UNITCOMBAT_NAVALRANGED','TXT_KEY_PROMOTION_NAVAL_RANGED_SHIP','UNIT_VENETIAN_GALLEASS','false','PROMOTION_NAVAL_RANGED_SHIP' UNION ALL
--巡洋舰
SELECT 'UNITCOMBAT_NAVALRANGED','TXT_KEY_PROMOTION_NAVAL_RANGED_CRUISER','UNIT_HEAVY_CRUISER','false','PROMOTION_NAVAL_RANGED_CRUISER' UNION ALL
--海军游猎
SELECT 'UNITCOMBAT_SUBMARINE','TXT_KEY_PROMOTION_NAVAL_HIT_AND_RUN','UNIT_BYZANTINE_DROMON','false','PROMOTION_NAVAL_HIT_AND_RUN' UNION ALL
--潜艇
SELECT 'UNITCOMBAT_SUBMARINE','TXT_KEY_PROMOTION_SUBMARINE_COMBAT','UNIT_SUBMARINE','false','PROMOTION_SUBMARINE_COMBAT' UNION ALL
--航母
SELECT 'UNITCOMBAT_CARRIER','TXT_KEY_PROMOTION_CARRIER_UNIT','UNIT_CARRIER','false','PROMOTION_CARRIER_UNIT' UNION ALL
--旗舰
SELECT 'UNITCOMBAT_NAVALRANGED','TXT_KEY_PROMOTION_NAVAL_CAPITAL_SHIP','UNIT_BATTLESHIP','false','PROMOTION_NAVAL_CAPITAL_SHIP' UNION ALL

--战斗机
SELECT 'UNITCOMBAT_FIGHTER','TXT_KEY_PROMOTION_ANTI_AIR_II','UNIT_FIGHTER','false','PROMOTION_ANTI_AIR_II' UNION ALL
--攻击机
SELECT 'UNITCOMBAT_ARCHER','TXT_KEY_PROMOTION_AIR_ATTACK','UNIT_DIVE_BOMBER','false','PROMOTION_AIR_ATTACK' UNION ALL
--战略轰炸机
SELECT 'UNITCOMBAT_ARCHER','TXT_KEY_PROMOTION_STRATEGIC_BOMBER','UNIT_JET_BOMBER','false','PROMOTION_STRATEGIC_BOMBER' ;